http_port:
  # The port used by the http service.
  "3000"
# IP addresses of whitelisted hosts. If the list is empty, all IP's can access the http service.
# Example: ["127.0.0.1", "192.168.0.1"]
ip_whitelist:
  []
dspace_host:
  # The DSpace api base url (no trailing slash)
  "http://localhost:8080/server"
solr_url:
  # The solr host (no trailing slash)
  "http://localhost:8983/solr"
solr_core:
  # The solr core name.
  "word_highlighting"
file_format:
  # Supports "alto" or "miniocr" formats. You should choose the more compact "miniocr" format
  # in most cases. When using "miniocr" the application will convert your alto files to miniocr
  # before indexing.
  "miniocr"
index_type:
  # You can use "lazy" or "full" indexing. If you choose "lazy" indexing the highlighter plugin
  # will retrieve ocr files from disk (lazy load) for each search result. This results in a
  # significantly smaller index but can have an effect on performance.
  # to disk
  "lazy"
escape_utf8:
  # When "lazy" loading ocr files from disk you can improve performance by converting utf8 to xml-encoded
  # ascii strings. This setting is only applied if you have also chosen "lazy" indexing. Converting to
  # ascii reduces CPU load when lazy loading word highlights.
  true
xml_file_location:
  # The path used for lazy index files. Solr will read ocr files from this directory if "lazy" indexing is used.
  "C:\path\to\ocr_files"
log_dir:
  # The location of your log directory.
  "C:\path\to\logs"
