#!/bin/sh

USAGE="$0 cvs-tag target"

# Just in case you need to 'socksify' etc
CVS_COMMAND="cvs"

# Check we have command-line arguments
if [ "$#" != "2" ]; then
        echo $USAGE
        exit 1
fi

mkdir tmp
cd tmp

echo "Checking out core code..."
$CVS_COMMAND -q export -r $1 dspace

# Don't need to include this script!
rm -f dspace/make-release-package

# Or silly cvsignore file
rm -f dspace/.cvsignore

echo "Creating tarball..."
mv dspace $2-source

tar -cf - $2-source | gzip -c > $2.tar.gz

echo "Cleaning up..."

cd ..
mv tmp/$2.tar.gz .
rm -r tmp

echo "Package created as $2.tar.gz"
