# LGTM Settings (https://lgtm.com/)
# For reference, see https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
# or template at https://lgtm.com/static/downloads/lgtm.template.yml

extraction:
  java:
    before_index:
      # Magic path from IncPlusPlus/bigtoolbox-io
      export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
    index:
      # Specify the Java version required to build the project
      java_version: 11
      build_command: ./lgtm-build.sh
