FROM tomcat:8-jre8

ENV TZ=America/New_York

EXPOSE 8080 8009

RUN apt-get update && \
    apt-get install -y \
        rsync \
        cron \
        postfix \
        vim \
        python3-lxml && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone