#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: "3.7"

services:
  dspace-cli:
    image: "dspace/dspace-cli:${DSPACE_VER:-dspace-6_x}"
    container_name: dspace-cli
    build:
      context: .
      dockerfile: Dockerfile.cli.jdk8
    #environment:
    volumes:
    - ./dspace/src/main/docker-compose/local.cfg:/dspace/config/local.cfg
    - assetstore:/dspace/assetstore
    entrypoint: /dspace/bin/dspace
    command: help
    networks:
      - dspacenet
    tty: true
    stdin_open: true

volumes:
  assetstore:

networks:
  dspacenet:
