# UMD-provided file running DSpace as part of a "Quick Build" setup
# This file is based on "Dockerfile.dev"
ARG JDK_VERSION=17
ARG DSPACE_VERSION=latest

# Step 1 - Run Maven Build
# UMD Customization
FROM docker.lib.umd.edu/drum:8_x-dev-base as build
# End UMD Customization
ARG TARGET_DIR=dspace-installer
WORKDIR /app

USER dspace
# Copy the DSpace source code (from local machine) into the workdir (excluding .dockerignore contents)
RUN rm -rf /app/dspace/modules/additions /app/dspace/modules/server
ADD --chown=dspace dspace/modules/additions /app/dspace/modules/additions
ADD --chown=dspace dspace/modules/server /app/dspace/modules/server
# Copy the dspace-installer directory to /install.  Clean up the build to keep the docker image small
# Maven flags here ensure that we skip building test environment and skip all code verification checks.
# These flags speed up this compilation as much as reasonably possible.
ENV MAVEN_FLAGS="-P-test-environment -Denforcer.skip=true -Dcheckstyle.skip=true -Dlicense.skip=true -Dxml.skip=true"
RUN mvn package -rf org.dspace:modules -pl '!org.dspace:dspace-iiif,!org.dspace:dspace-oai,!org.dspace:dspace-rdf,!org.dspace:dspace-sword,!org.dspace:dspace-swordv2' ${MAVEN_FLAGS} && \
  mv /app/dspace/target/${TARGET_DIR}/* /install && \
  mvn clean
# Remove the server webapp to keep image small.
RUN rm -rf /install/webapps/server/

# Step 2 - Run Ant Deploy
# UMD Customization
FROM docker.lib.umd.edu/drum-ant:latest as ant_build
# End UMD Customization
ARG TARGET_DIR=dspace-installer
# COPY the /install directory from 'build' container to /dspace-src in this container
COPY --from=build /install /dspace-src
WORKDIR /dspace-src

# UMD Customization
# Ant is installed as part of the "drum-ant" Docker image
# End UMD Customization

# Run necessary 'ant' deploy scripts
RUN ant init_installation update_configs update_code update_webapps

# Step 3 - Start up DSpace via Runnable JAR
FROM eclipse-temurin:${JDK_VERSION}
# NOTE: DSPACE_INSTALL must align with the "dspace.dir" default configuration.
ENV DSPACE_INSTALL=/dspace
# Copy the /dspace directory from 'ant_build' container to /dspace in this container
COPY --from=ant_build /dspace $DSPACE_INSTALL
WORKDIR $DSPACE_INSTALL
# Expose Tomcat port
EXPOSE 8080
# Give java extra memory (2GB)
ENV JAVA_OPTS=-Xmx2000m
# UMD Customization
ENV TZ=America/New_York

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        rsync \
        cron \
        csh \
        postfix \
        s-nail \
        libgetopt-complete-perl \
        libconfig-properties-perl \
        vim \
        python3-lxml && \
    mkfifo /var/spool/postfix/public/pickup && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# End UMD Customization
# On startup, run DSpace Runnable JAR
ENTRYPOINT ["java", "-jar", "webapps/server-boot.jar", "--dspace.dir=$DSPACE_INSTALL"]
