#!/bin/tcsh 
set echo 
rm -rf dspace-api/target/classes/org/dspace/app/bulkdo
(cd dspace-api; mvn package)
cp -p dspace-api/target/dspace-api-1.8.4-SNAPSHOT.jar  $DSPACE_HOME/lib/
ls -l  $DSPACE_HOME/lib/dspace-api*SNAPSHOT*

