#!/usr/local/bin/perl -n

# Cleanup CISSM data after it has been converted to dc xml:
#  1. Change name format
#  2. Get rid of garbage data.
#  3. Remove xml elements from text

#  Name patterns in the cissm data
#
#   1 N N with N N
#  91 N N
#  15 N N and N N
#   1 N N and N N N
#   2 N N and N N. N
#   4 N N and N.N. N
#   4 N N N
#   1 N N'N
#   1 N N, N N, and N N
#   1 N N, N N, and N N. N
#   1 N N, N N, N N N N, N N
#   1 N N, N N, N N, N N
#   1 N N, N N, N N. N, N N and N N
#   1 N N, N N-N, and N N
#   1 N N, N N. N, N N and N N
#  38 N N. N
#   2 N N. N and N N
#   3 N N. N and N N. N
#   1 N N. N and N.N. N
#   1 N N. N, N N, N N, N N, N N
#   1 N N.N. N
#   1 N.N. N

s/&lt;.*?&gt;//g;
s/&amp;nbsp;/ /g;
s/&amp;amp;/&amp;/g;

s/(qualifier=".*?") (element=".*?")/$2 $1/;
s/\342\200\232\303\204\303\264/&quot;/g; 
s/\342\200\232\303\204\303./"/g; #"
s/[\200-\377]*//g;

if (m|(^<dcvalue element="contributor" qualifier="author">)(.*)(</dcvalue>)$|) {
    $begin = $1;
    $a = $2;
    $end = $3;

    @a = split /, +and +|, +| +and +| +with +/, $a;

    # last name first
    @a2 = map {
	$a = $_;

	if ($a eq "Members of Workshop") {
	    $_ = $a;

	} else {
	    @n = split / +/, $a;

	    $lname = pop @n;
	    unshift @n, "$lname,";

	    $_ = join ' ', @n;
	} 
    } @a;

    foreach $a (@a2) {
	print $begin . $a . $end . "\n";
    }

} else {
    print;
}




