- name: Definer *.brage.unit.no virtualhost
  set_fact:
    bragevirtualhost: "{{ (fase == 'produksjon') | ternary(kunde ~ '.brage.unit.no', 'brage-' ~ fase ~ '.bibsys.no') }}"

- name: Create target paths
  file:
    mode: "755"
    path: "{{item}}"
    state: directory
  loop:
    - /brage/{{ kunde }}
    - /brage/{{ kunde }}/app
    - /brage/{{ kunde }}/data
    - /brage/{{ kunde }}/install
    - /brage/{{ kunde }}/tmp

- name: Deploy DSpace Installer
  synchronize:
    delete: yes
    dest: /brage/{{ kunde }}/install/dspace-installer/
    src: "{{ jenkins_workspace }}/dspace/target/dspace-installer/"

- name: Customize theme - create CSS dir
  file:
    path: /brage/{{ kunde }}/install/dspace-installer/custom_css_assembly
    state: directory

- name: Customize theme - copy base CSS
  copy:
    src: "{{ jenkins_workspace }}/dspace/target/dspace-installer/webapps/xmlui/themes/Mirage2/styles/main.css"
    dest: /brage/{{ kunde }}/install/dspace-installer/custom_css_assembly/1.css

- name: Customize theme - copy custom CSS
  copy:
    src: "{{ jenkins_workspace }}/customizations/themes/{{ kunde }}/style.css"
    dest: /brage/{{ kunde }}/install/dspace-installer/custom_css_assembly/2.css

- name: Customize theme - add logo, favicon and other images
  synchronize:
    dest: /brage/{{ kunde }}/install/dspace-installer/webapps/xmlui/themes/Mirage2/
    src: "{{ jenkins_workspace }}/customizations/themes/{{ kunde }}/overlay/"

- name: Customize theme - assemble CSS
  assemble:
    src: /brage/{{ kunde }}/install/dspace-installer/custom_css_assembly
    dest: /brage/{{ kunde }}/install/dspace-installer/webapps/xmlui/themes/Mirage2/styles/main.css

- name: Create local.cfg
  template:
    src: local.cfg.j2
    dest: /brage/{{ kunde }}/install/dspace-installer/config/local.cfg

- name: Make sure brage-{{ kunde }} database is present
  postgresql_db:
    lc_collate: nb_NO.utf8
    lc_ctype: nb_NO.utf8
    login_host: "{{ DatabaseHost[fase] }}"
    login_user: "{{ lookup('hashi_vault', 'secret=secret/service/brage/' + fase + ':db_username auth_method=approle role_id=brage-client-' + fase + ' secret_id=' + vault_secret + ' url=https://vault.bibsys.no:8200')}}"
    login_password: "{{ lookup('hashi_vault', 'secret=secret/service/brage/' + fase + ':db_password auth_method=approle role_id=brage-client-' + fase + ' secret_id=' + vault_secret + ' url=https://vault.bibsys.no:8200')}}"
    name: brage-{{ kunde }}
    template: template0
  when: fase == "produksjon"
    
- name: Notify Slack
  slack:
    channel: "{{ slack_channel | default(SlackConfig.channel) }}"
    icon_emoji: "{{ SlackConfig.icon }}"
    msg: "`[{{kunde}}]` Installasjonspakke ferdig. Starter installasjon."
    token: "{{ SlackConfig.token }}"
    username: "{{ SlackConfig.sender }}"

- name: Install application
  register: result
  shell: "ant -buildfile /brage/{{ kunde }}/install/dspace-installer/build.xml fresh_install"
  ignore_errors: yes

- name: Fail on ant failure
  fail:
    msg: "stderr: {{ result.stderr }} stdout: {{ result.stdout }}"
  when: result.rc > 0

- name: Update configs
  register: result
  shell: "ant -buildfile /brage/{{ kunde }}/install/dspace-installer/build.xml update_configs"
  ignore_errors: yes

- name: Fail on ant failure
  fail:
    msg: "stderr: {{ result.stderr }} stdout: {{ result.stdout }}"
  when: result.rc > 0

- name: Undeploy Apps
  shell: "curl -s -n 'http://localhost:8080/manager/text/undeploy?path=/{{kunde}}-{{item}}'"
  loop:
    - xmlui
    - oai
    - rest

- name: Undeploy SOLR
  shell: "curl -s -n 'http://localhost:9080/manager/text/undeploy?path=/{{kunde}}-solr'"

- name: Look for database migrations
  shell: "/brage/{{ kunde }}/app/bin/dspace map-workflows"

- name: Look for database migrations
  shell: "/brage/{{ kunde }}/app/bin/dspace database info"
  register: dbinfo

- name: Run database migrations
  shell: "/brage/{{ kunde }}/app/bin/dspace {{ item }}"
  when: dbinfo.stdout.find("pending") != -1
  loop:
    - "database migrate"
    - "index-discovery -b"
    - "oai import -c -o"

- name: Deploy SOLR
  synchronize:
    delete: yes
    dest: /srv/tomcat-solr/webapps/{{ kunde }}-solr/
    src: /brage/{{ kunde }}/app/webapps/solr/
  delegate_to: "{{inventory_hostname}}"
  
- name: Deploy Apps
  synchronize:
    delete: yes
    dest: /srv/tomcat-xmlui-oai/webapps/{{ kunde }}-{{item}}/
    src: /brage/{{ kunde }}/app/webapps/{{item}}/
  delegate_to: "{{inventory_hostname}}"
  with_items:
    - oai
    - xmlui
    - rest

- name: Deploy maintenance scripts
  copy:
    src: ../customizations/maintenance-scripts/
    dest: /brage/{{ kunde }}/app/bibsys-scripts

- name: Deploy FEIDE authentication properties
  copy:
    dest: /brage/{{ kunde }}/app/config/feide.properties
    content: |
      SP_ENTITY_ID={{ FeideEntityID }}
      IDP_BASEPATH=https://{{ FeideConfig[fase]["IDP"] }}

- name: Deploy handle server properties
  template:
    dest: /brage/{{ kunde }}/app/config/handleserver.properties
    src: handleserver.properties.j2

- name: Notify Slack
  slack:
    channel: "{{ slack_channel | default(SlackConfig.channel) }}"
    icon_emoji: "{{ SlackConfig.icon }}"
    msg: "`[{{kunde}}]` Installasjon utført."
    token: "{{ SlackConfig.token }}"
    username: "{{ SlackConfig.sender }}"
