- hosts: webservers
  gather_facts: false
  tasks:
    - name: Bootstrap and sanity checks
      import_tasks:
        file: bootstrap.yml

    - name: Utfør operasjonen for alle kunder på den angitte appserveren
      include_tasks: webconf.yml
      loop: "{{ hostvars[appserver]['kunder'] }}"
