- name: Copy VirtualHost configuration file
  template:
    src: virtualhost.conf.j2
    dest: "{{ webconfpath | default('/etc/httpd/conf/vhosts/active/brage') }}/{{ kunde }}.conf"
    mode: 0644

- name: Copy custom configuration file
  template:
    src: "../customizations/customvhosts/{{ item }}"
    dest: "{{ webconfpath | default('/etc/httpd/conf/vhosts/active/brage') }}/{{ item }}"
    mode: 0644
    force: no
  loop: "{{ kundedata[kunde]['customvhostconfigs'] }}"
  when: kundedata[kunde]["customvhostconfigs"] is defined

- name: Publish SAML metadata
  template:
    src: feide-metadata.j2.xml
    dest: /home/httpd/domains/brage.unit.no/saml-metadata/{{ kunde }}.xml
