// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.edu.unlp.sedici.sedici2003.model;

import java.io.Serializable;

privileged aspect CarpetasDocumentosPK_Roo_Serializable {
    
    declare parents: CarpetasDocumentosPK implements Serializable;
    
    private static final long CarpetasDocumentosPK.serialVersionUID = 1L;
    
}
