/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 06:33:14 PM CEST 
//


package org.dspace.authority.orcid.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}application-orcid"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}application-name"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}application-website"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}approval-date"/>
 *         &lt;element ref="{http://www.orcid.org/ns/orcid}scope-paths"/>
 *         &lt;element name="application-group-orcid" type="{http://www.orcid.org/ns/orcid}orcid-id"/>
 *         &lt;element name="application-group-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationOrcid",
    "applicationName",
    "applicationWebsite",
    "approvalDate",
    "scopePaths",
    "applicationGroupOrcid",
    "applicationGroupName"
})
@XmlRootElement(name = "application-summary")
public class ApplicationSummary {

    @XmlElement(name = "application-orcid", required = true)
    protected OrcidId applicationOrcid;
    @XmlElement(name = "application-name", required = true)
    protected ApplicationName applicationName;
    @XmlElement(name = "application-website", required = true)
    protected ApplicationWebsite applicationWebsite;
    @XmlElement(name = "approval-date", required = true)
    protected ApprovalDate approvalDate;
    @XmlElement(name = "scope-paths", required = true)
    protected ScopePaths scopePaths;
    @XmlElement(name = "application-group-orcid", required = true)
    protected OrcidId applicationGroupOrcid;
    @XmlElement(name = "application-group-name", required = true)
    protected String applicationGroupName;

    /**
     * Gets the value of the applicationOrcid property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    public OrcidId getApplicationOrcid() {
        return applicationOrcid;
    }

    /**
     * Sets the value of the applicationOrcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    public void setApplicationOrcid(OrcidId value) {
        this.applicationOrcid = value;
    }

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationName }
     *     
     */
    public ApplicationName getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationName }
     *     
     */
    public void setApplicationName(ApplicationName value) {
        this.applicationName = value;
    }

    /**
     * Gets the value of the applicationWebsite property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationWebsite }
     *     
     */
    public ApplicationWebsite getApplicationWebsite() {
        return applicationWebsite;
    }

    /**
     * Sets the value of the applicationWebsite property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationWebsite }
     *     
     */
    public void setApplicationWebsite(ApplicationWebsite value) {
        this.applicationWebsite = value;
    }

    /**
     * Gets the value of the approvalDate property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalDate }
     *     
     */
    public ApprovalDate getApprovalDate() {
        return approvalDate;
    }

    /**
     * Sets the value of the approvalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalDate }
     *     
     */
    public void setApprovalDate(ApprovalDate value) {
        this.approvalDate = value;
    }

    /**
     * Gets the value of the scopePaths property.
     * 
     * @return
     *     possible object is
     *     {@link ScopePaths }
     *     
     */
    public ScopePaths getScopePaths() {
        return scopePaths;
    }

    /**
     * Sets the value of the scopePaths property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScopePaths }
     *     
     */
    public void setScopePaths(ScopePaths value) {
        this.scopePaths = value;
    }

    /**
     * Gets the value of the applicationGroupOrcid property.
     * 
     * @return
     *     possible object is
     *     {@link OrcidId }
     *     
     */
    public OrcidId getApplicationGroupOrcid() {
        return applicationGroupOrcid;
    }

    /**
     * Sets the value of the applicationGroupOrcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrcidId }
     *     
     */
    public void setApplicationGroupOrcid(OrcidId value) {
        this.applicationGroupOrcid = value;
    }

    /**
     * Gets the value of the applicationGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationGroupName() {
        return applicationGroupName;
    }

    /**
     * Sets the value of the applicationGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationGroupName(String value) {
        this.applicationGroupName = value;
    }

}
