#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: "3.7"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto:loadsql
    environment:
      # Double underbars in env names will be replaced with periods for apache commons
      - LOADSQL=https://www.dropbox.com/s/xh3ack0vg0922p2/configurable-entities-2019-05-08.sql?dl=1
