#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: "3.7"

#
# Overrides the default "dspacedb" container behavior to load a local SQL file into PostgreSQL.
#
# This can be used to restore a "dspacedb" container from a pg_dump, or during upgrade to a new version of PostgreSQL.
services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto:dspace-7_x-loadsql
    environment:
      # Location where the dump SQL file will be available on the running container
      - LOCALSQL=/tmp/pgdump.sql
    volumes:
      # Volume which shares a local SQL file at "./pgdump.sql" to the running container
      # IF YOUR LOCAL FILE HAS A DIFFERENT NAME (or is in a different location), then change the "./pgdump.sql"
      # portion of this line.
      - ./pgdump.sql:/tmp/pgdump.sql

