#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

#
# Test environment for DSpace + Shibboleth (running via mod_shib in Apache). See README for instructions.
# This should NEVER be used in production scenarios.
#
networks:
  # Default to using network named 'dspacenet' from docker-compose.yml.
  # Its full name will be prepended with the project name (e.g. "-p d7" means it will be named "d7_dspacenet")
  default:
    name: ${COMPOSE_PROJECT_NAME}_dspacenet
    external: true
services:
  dspace-shibboleth:
    container_name: dspace-shibboleth
    depends_on:
      - dspace
    image: dspace/dspace-shibboleth
    build:
      # Must be relative to root, so that it can be built alongside [src]/docker-compose.yml
      context: ./dspace/src/main/docker/dspace-shibboleth
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    stdin_open: true
    tty: true
    environment:
      # Default to using "localhost" for Apache & Shibboleth
      # However, you can override this via the "DSPACE_HOSTNAME" environment variable.
      # e.g., if using ngrok.com as a proxy, set to ngrok.io server: "DSPACE_HOSTNAME=[random-string].ngrok.io"
      APACHE_SERVER_NAME: '${DSPACE_HOSTNAME:-localhost}'
