#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

version: '3.7'
networks:
  dspacenet:
services:
  dspace-shibboleth:
    container_name: dspace-shibboleth
    depends_on:
      - dspace
    image: dspace/dspace-shibboleth
    networks:
      dspacenet:
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    stdin_open: true
    tty: true
