#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

#
# Test environment for DSpace + Matomo support. See README for instructions.
# This should NEVER be used in production scenarios.
#
networks:
  # Default to using network named 'dspacenet' from docker-compose.yml.
  # Its full name will be prepended with the project name (e.g. "-p d7" means it will be named "d7_dspacenet")
  default:
    name: ${COMPOSE_PROJECT_NAME}_dspacenet
    external: true
services:
  database:
    image: mariadb:10.11.5-jammy
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=matomo
      - MYSQL_PASSWORD=matomo
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
  matomo:
    image: matomo:5.2.2-apache
    environment:
      - MATOMO_DATABASE_HOST=database
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=matomo
      - MATOMO_DATABASE_DBNAME=matomo
    ports:
      - published: 8081
        target: 80