#
# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source
# tree and available online at
#
# http://www.dspace.org/license/
#

#
# Test environment for DSpace + OIDC (OpenID Connect) authentication by using Keycloak. See README for instructions.
# This should NEVER be used in production scenarios.
#
version: '3.7'
networks:
  dspacenet:
services:
  dspace-oidc:
    container_name: dspace-oidc
    depends_on:
      - dspace
    # https://github.com/keycloak/keycloak-containers/blob/main/server/README.md
    # https://hub.docker.com/r/jboss/keycloak/tags
    image: jboss/keycloak:16.1.0
    networks:
      dspacenet:
    # Available at locolhost:8180/
    ports:
      - published: 8180
        target: 8080
    environment:
      # Default Admin Acct for Keycloak
      KEYCLOAK_USER: '${KEYCLOAK_USER:-admin}'
      KEYCLOAK_PASSWORD: '${KEYCLOAK_PASSWORD:-admin}'
