FROM docker.lib.umd.edu/solr:4.10.4-umd-1.0

COPY --chown=solr ./search /opt/solr/server/solr/configsets/search
COPY --chown=solr ./statistics /opt/solr/server/solr/configsets/statistics
COPY --chown=solr ./oai /opt/solr/server/solr/configsets/oai
