# Mapping between DSpace common publication's types and the type supported by ORCID
annotation = other
Animation = other
Article = journal-article
bachelor\ thesis = dissertation-thesis
bibliography = other
Book = book
book = book
Book\ chapter = book-chapter
Book\ Part = book-chapter
book\ part = book-chapter
book\ review = book-review
cartographic\ material = cartographic-material
conference\ object = conference-output
conference\ paper = conference-paper
conference\ paper\ not\ in\ proceedings = conference-paper
conference\ poster = conference-poster
conference\ poster\ not\ in\ proceedings = conference-poster
conference\ presentation = conference-presentation
conference\ proceedings = conference-proceedings
contribution\ to\ journal = journal-article
data\ management\ plan = data-management-plan
data\ paper = journal-article
Dataset = data-set
dataset = data-set
doctoral\ thesis = dissertation-thesis
editorial = journal-article
internal\ report = report
journal = journal-issue
journal\ article = journal-article
lecture = lecture-speech
letter = other
letter\ to\ the\ editor = journal-article
Learning\ Object = learning-object
master\ thesis = dissertation-thesis
Image = image
image = image
Image,\ 3-D = image
Journal = journal-issue
Map = cartographic-material
map = cartographic-material
magazine\ article = magazine-article
memorandum = report
Musical\ Score = musical-composition
musical\ composition = musical-composition
musical\ notation = musical-composition
newspaper\ article = newspaper-article
other\ type\ of\ report = report
patent = patent
periodical = journal-issue
Plan\ or\ blueprint = other
policy\ report = report
Preprint = preprint
preprint = preprint
Presentation = other
project\ deliverable = report
Recording,\ acoustical = sound
Recording,\ musical = sound
Recording,\ oral = sound
report = report
report\ part = report
report\ to\ funding\ agency = report
research\ article = journal-article
research\ proposal = other
research\ report = report
research\ software = software
review = other
review\ article = journal-article
Software = software
software = software
software\ paper = journal-article
sound = sound
still\ image = image
technical\ documentation = report
Technical\ Report = report
technical\ report = report
text = other
Thesis = dissertation-thesis
thesis = dissertation-thesis
Video = moving-image
video = moving-image
website = website
Working\ Paper = working-paper
working\ paper = working-paper
Other = other
