# Mapping between work type supported by ORCID and the DSpace common publication's types
annotation = Other
artistic-performance = Other
blog-post = Other
book = Book
book-chapter = Book chapter
book-review = Other
cartographic-material = Other
clinical-study = Other
conference-abstract = Other
conference-output = Other
conference-paper = Other
conference-poster = Other
conference-presentation = Other
conference-proceedings = Other
data-management-plan = Other
data-set = Dataset
design = Other
dictionary-entry = Other
disclosure = Other
dissertation-thesis = Thesis
edited-book = Book
encyclopedia-entry = Other
image = Other
invention = Other
journal-article = Article
journal-issue = Journal
learning-object = Other
lecture-speech = Other
license = Other
magazine-article = Article
manual = Other
moving-image = Other
musical-composition = Other
newsletter-article = Article
newspaper-article = Article
online-resource = Other
other = Other
patent = Other
physical-object = Other
preprint = Preprint
public-speech = Other
registered-copyright = Other
report = Other
research-technique = Other
research-tool = Other
review = Other
software = Software
sound = Other
spin-off-company = Other
standards-and-policy = Other
supervised-student-publication = Other
technical-standard = Other
test = Other
trademark = Other
transcription = Other
translation = Other
undefined = Other
website = Other
working-paper = Working Paper
