/**
 * =============================================================================
 *
 * ORCID (R) Open Source
 * http://orcid.org
 *
 * Copyright (c) 2012-2014 ORCID, Inc.
 * Licensed under an MIT-Style License (MIT)
 * http://orcid.org/open-source-license
 *
 * This copyright and license information (including a link to the full license)
 * shall be included in its entirety in all copies or substantial portion of
 * the software.
 *
 * =============================================================================
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.23 at 12:45:35 PM BST 
//

package org.orcid.jaxb.model.clientgroup;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.orcid.jaxb.model.clientgroup package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GroupName_QNAME = new QName("http://www.orcid.org/ns/orcid", "group-name");
    private final static QName _GroupOrcid_QNAME = new QName("http://www.orcid.org/ns/orcid", "group-orcid");
    private final static QName _ClientId_QNAME = new QName("http://www.orcid.org/ns/orcid", "client-id");
    private final static QName _ShortDescription_QNAME = new QName("http://www.orcid.org/ns/orcid", "short-description");
    private final static QName _ClientSecret_QNAME = new QName("http://www.orcid.org/ns/orcid", "client-secret");
    private final static QName _Email_QNAME = new QName("http://www.orcid.org/ns/orcid", "email");
    private final static QName _Website_QNAME = new QName("http://www.orcid.org/ns/orcid", "website");
    private final static QName _RedirectUri_QNAME = new QName("http://www.orcid.org/ns/orcid", "redirect-uri");
    private final static QName _DisplayName_QNAME = new QName("http://www.orcid.org/ns/orcid", "display-name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.orcid.jaxb.model.clientgroup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.orcid.jaxb.model.clientgroup.RedirectUris }
     *
     */
    public RedirectUris createRedirectUris() {
        return new RedirectUris();
    }

    /**
     * Create an instance of {@link org.orcid.jaxb.model.clientgroup.OrcidClient }
     *
     */
    public OrcidClient createOrcidClient() {
        return new OrcidClient();
    }

    /**
     * Create an instance of {@link OrcidClientGroup }
     *
     */
    public OrcidClientGroup createOrcidClientGroup() {
        return new OrcidClientGroup();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "group-name")
    public JAXBElement<String> createGroupName(String value) {
        return new JAXBElement<String>(_GroupName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "group-orcid")
    public JAXBElement<String> createGroupOrcid(String value) {
        return new JAXBElement<String>(_GroupOrcid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "client-id")
    public JAXBElement<String> createClientId(String value) {
        return new JAXBElement<String>(_ClientId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "short-description")
    public JAXBElement<String> createShortDescription(String value) {
        return new JAXBElement<String>(_ShortDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "client-secret")
    public JAXBElement<String> createClientSecret(String value) {
        return new JAXBElement<String>(_ClientSecret_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "website")
    public JAXBElement<String> createWebsite(String value) {
        return new JAXBElement<String>(_Website_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "redirect-uri")
    public JAXBElement<String> createRedirectUri(String value) {
        return new JAXBElement<String>(_RedirectUri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orcid.org/ns/orcid", name = "display-name")
    public JAXBElement<String> createDisplayName(String value) {
        return new JAXBElement<String>(_DisplayName_QNAME, String.class, null, value);
    }

}
