--   The contents of this file are subject to the license and copyright
--   detailed in the LICENSE and NOTICE files at the root of the source
--   tree and available online at
--   
--   https://github.com/CILEA/dspace-cris/wiki/License
--
-- SQL commands to upgrade the database schema to a live DSpace-CRIS
--
-- DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST.
-- DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST.
-- DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST. DUMP YOUR DATABASE FIRST.
create table cris_do (id int4 not null, crisID varchar(255), sourceID varchar(255), sourceRef varchar(255), status boolean, uuid varchar(255) not null, timestampCreated timestamp, timestampLastModified timestamp, typo_id int4, primary key (id));
create table cris_do_box (id int4 not null, collapsed boolean not null, externalJSP varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), unrelevant boolean not null, visibility int4, typeDef_id int4, primary key (id));
create table cris_do_box2con (cris_do_box_id int4 not null, jdyna_containable_id int4 not null);
create table cris_do_box2policygroup (box_id int4 not null, authorizedGroup varchar(255));
create table cris_do_box2policysingle (box_id int4 not null, authorizedSingle varchar(255));
create table cris_do_etab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, displayTab_id int4, typeDef_id int4, primary key (id));
create table cris_do_etab2box (cris_do_etab_id int4 not null, cris_do_box_id int4 not null);
create table cris_do_etab2policygroup (etab_id int4 not null, authorizedGroup varchar(255));
create table cris_do_etab2policysingle (etab_id int4 not null, authorizedSingle varchar(255));
create table cris_do_no (id int4 not null, endDate timestamp, startDate timestamp, positionDef int4, preferred boolean, status boolean, timestampCreated timestamp, timestampLastModified timestamp, uuid varchar(255) not null, scopeDef_id int4, sourceID varchar(255), sourceRef varchar(255), parent_id int4, typo_id int4, primary key (id));
create table cris_do_no_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_do_no_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_do_no_tp (id int4 not null, label varchar(255), shortName varchar(255), accessLevel int4, help varchar(4000), inline boolean not null, mandatory boolean not null, newline boolean not null, priority int4 not null, repeatable boolean not null, primary key (id));
create table cris_do_no_tp2pdef (cris_do_no_tp_id int4 not null, cris_do_no_pdef_id int4 not null);
create table cris_do_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_do_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_do_tab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, typeDef_id int4, primary key (id));
create table cris_do_tab2box (cris_do_tab_id int4 not null, cris_do_box_id int4 not null);
create table cris_do_tab2policygroup (tab_id int4 not null, authorizedGroup varchar(255));
create table cris_do_tab2policysingle (tab_id int4 not null, authorizedSingle varchar(255));
create table cris_do_tp (id int4 not null, label varchar(255), shortName varchar(255), primary key (id));
create table cris_do_tp2notp (cris_do_tp_id int4 not null, cris_do_no_tp_id int4 not null);
create table cris_do_tp2pdef (cris_do_tp_id int4 not null, cris_do_pdef_id int4 not null);
create table cris_do_wfile (id int4 not null, fileDescription text, labelAnchor varchar(255), showPreview boolean not null, widgetSize int4, useInStatistics boolean not null, primary key (id));
create table cris_do_wpointer (id int4 not null, display text, filtro text, indexName varchar(255), widgetSize int4, target varchar(255), urlPath varchar(255), filterExtended text, primary key (id));
create table cris_metrics (id int4 not null, endDate timestamp, last boolean not null, metricCount float8 not null, metricType varchar(255), remark text, resourceId int4, resourceTypeId int4, startDate timestamp, timestampCreated timestamp, timestampLastModified timestamp, uuid varchar(255), primary key (id));
create table cris_orcid_history (id int4 not null, entityId int4, entityUuid varchar(255), owner varchar(255), putCode varchar(255), responseMessage text, lastAttempt timestamp, lastSuccess timestamp, typeId int4, primary key (id));
create table cris_orcid_queue (id int4 not null, entityId int4, fastlookupObjectName text, fastlookupUuid varchar(255), mode varchar(255), owner varchar(255), typeId int4, primary key (id));
create table cris_orgunit (id int4 not null, crisID varchar(255), sourceID varchar(255), sourceRef varchar(255), status boolean, uuid varchar(255) not null, timestampCreated timestamp, timestampLastModified timestamp, primary key (id));
create table cris_ou_box (id int4 not null, collapsed boolean not null, externalJSP varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), unrelevant boolean not null, visibility int4, primary key (id));
create table cris_ou_box2con (cris_ou_box_id int4 not null, jdyna_containable_id int4 not null);
create table cris_ou_box2policygroup (box_id int4 not null, authorizedGroup varchar(255));
create table cris_ou_box2policysingle (box_id int4 not null, authorizedSingle varchar(255));
create table cris_ou_etab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, displayTab_id int4, primary key (id));
create table cris_ou_etab2box (cris_ou_etab_id int4 not null, cris_ou_box_id int4 not null);
create table cris_ou_etab2policygroup (etab_id int4 not null, authorizedGroup varchar(255));
create table cris_ou_etab2policysingle (etab_id int4 not null, authorizedSingle varchar(255));
create table cris_ou_no (id int4 not null, endDate timestamp, startDate timestamp, positionDef int4, preferred boolean, status boolean, timestampCreated timestamp, timestampLastModified timestamp, uuid varchar(255) not null, scopeDef_id int4, sourceID varchar(255), sourceRef varchar(255), parent_id int4, typo_id int4, primary key (id));
create table cris_ou_no_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_ou_no_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_ou_no_tp (id int4 not null, label varchar(255), shortName varchar(255), accessLevel int4, help varchar(4000), inline boolean not null, mandatory boolean not null, newline boolean not null, priority int4 not null, repeatable boolean not null, primary key (id));
create table cris_ou_no_tp2pdef (cris_ou_no_tp_id int4 not null, cris_ou_no_pdef_id int4 not null);
create table cris_ou_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_ou_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_ou_tab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, primary key (id));
create table cris_ou_tab2box (cris_ou_tab_id int4 not null, cris_ou_box_id int4 not null);
create table cris_ou_tab2policygroup (tab_id int4 not null, authorizedGroup varchar(255));
create table cris_ou_tab2policysingle (tab_id int4 not null, authorizedSingle varchar(255));
create table cris_ou_wfile (id int4 not null, fileDescription text, labelAnchor varchar(255), showPreview boolean not null, widgetSize int4, useInStatistics boolean not null, primary key (id));
create table cris_ou_wpointer (id int4 not null, display text, filtro text, indexName varchar(255), widgetSize int4, target varchar(255), urlPath varchar(255), primary key (id));
create table cris_pj_box (id int4 not null, collapsed boolean not null, externalJSP varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), unrelevant boolean not null, visibility int4, primary key (id));
create table cris_pj_box2con (cris_pj_box_id int4 not null, jdyna_containable_id int4 not null);
create table cris_pj_box2policygroup (box_id int4 not null, authorizedGroup varchar(255));
create table cris_pj_box2policysingle (box_id int4 not null, authorizedSingle varchar(255));
create table cris_pj_etab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, displayTab_id int4, primary key (id));
create table cris_pj_etab2box (cris_pj_etab_id int4 not null, cris_pj_box_id int4 not null);
create table cris_pj_etab2policygroup (etab_id int4 not null, authorizedGroup varchar(255));
create table cris_pj_etab2policysingle (etab_id int4 not null, authorizedSingle varchar(255));
create table cris_pj_no (id int4 not null, endDate timestamp, startDate timestamp, positionDef int4, preferred boolean, status boolean, timestampCreated timestamp, timestampLastModified timestamp, uuid varchar(255) not null, scopeDef_id int4, sourceID varchar(255), sourceRef varchar(255), parent_id int4, typo_id int4, primary key (id));
create table cris_pj_no_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_pj_no_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_pj_no_tp (id int4 not null, label varchar(255), shortName varchar(255), accessLevel int4, help varchar(4000), inline boolean not null, mandatory boolean not null, newline boolean not null, priority int4 not null, repeatable boolean not null, primary key (id));
create table cris_pj_no_tp2pdef (cris_pj_no_tp_id int4 not null, cris_pj_no_pdef_id int4 not null);
create table cris_pj_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_pj_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_pj_tab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, primary key (id));
create table cris_pj_tab2box (cris_pj_tab_id int4 not null, cris_pj_box_id int4 not null);
create table cris_pj_tab2policygroup (tab_id int4 not null, authorizedGroup varchar(255));
create table cris_pj_tab2policysingle (tab_id int4 not null, authorizedSingle varchar(255));
create table cris_pj_wfile (id int4 not null, fileDescription text, labelAnchor varchar(255), showPreview boolean not null, widgetSize int4, useInStatistics boolean not null, primary key (id));
create table cris_pj_wpointer (id int4 not null, display text, filtro text, indexName varchar(255), widgetSize int4, target varchar(255), urlPath varchar(255), primary key (id));
create table cris_pmc_citation (pubmedID int4 not null, timestampCreated timestamp, timestampLastModified timestamp, primary key (pubmedID));
create table cris_pmc_citation2record (cris_pmc_citation_pubmedid int4 not null, pmcRecords_pmcID int4 not null);
create table cris_pmc_citation_itemids (cris_pmc_citation_pubmedid int4 not null, element int4);
create table cris_pmc_record (pmcID int4 not null, authors text, publicationnote text, title text, primary key (pmcID));
create table cris_pmc_record_handles (cris_pmc_record_pmcid int4 not null, element varchar(255));
create table cris_pmc_record_pubmedids (cris_pmc_record_pmcid int4 not null, element int4);
create table cris_project (id int4 not null, crisID varchar(255), sourceID varchar(255), sourceRef varchar(255), status boolean, uuid varchar(255) not null, timestampCreated timestamp, timestampLastModified timestamp, primary key (id));
create table cris_relpref (id int4 not null, itemID int4, priority int4 not null, relationType varchar(255), sourceUUID varchar(255), status varchar(255), targetUUID varchar(255), primary key (id));
create table cris_rp_box (id int4 not null, collapsed boolean not null, externalJSP varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), unrelevant boolean not null, visibility int4, primary key (id));
create table cris_rp_box2con (cris_rp_box_id int4 not null, jdyna_containable_id int4 not null);
create table cris_rp_box2policygroup (box_id int4 not null, authorizedGroup varchar(255));
create table cris_rp_box2policysingle (box_id int4 not null, authorizedSingle varchar(255));
create table cris_rp_etab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, displayTab_id int4, primary key (id));
create table cris_rp_etab2box (cris_rp_etab_id int4 not null, cris_rp_box_id int4 not null);
create table cris_rp_etab2policygroup (etab_id int4 not null, authorizedGroup varchar(255));
create table cris_rp_etab2policysingle (etab_id int4 not null, authorizedSingle varchar(255));
create table cris_rp_no (id int4 not null, endDate timestamp, startDate timestamp, positionDef int4, preferred boolean, status boolean, timestampCreated timestamp, timestampLastModified timestamp, uuid varchar(255) not null, scopeDef_id int4, sourceID varchar(255), sourceRef varchar(255), parent_id int4, typo_id int4, primary key (id));
create table cris_rp_no_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_rp_no_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_rp_no_tp (id int4 not null, label varchar(255), shortName varchar(255), accessLevel int4, help varchar(4000), inline boolean not null, mandatory boolean not null, newline boolean not null, priority int4 not null, repeatable boolean not null, primary key (id));
create table cris_rp_no_tp2pdef (cris_rp_no_tp_id int4 not null, cris_rp_no_pdef_id int4 not null);
create table cris_rp_pdef (id int4 not null, accessLevel int4, advancedSearch boolean not null, fieldmin_col int4, fieldmin_col_unit varchar(255), fieldmin_row_unit varchar(255), fieldmin_row int4, help text, label varchar(255), labelMinSize int4 not null, labelMinSizeUnit varchar(255), mandatory boolean not null, newline boolean not null, onCreation boolean, priority int4 not null, repeatable boolean not null, shortName varchar(255), showInList boolean not null, simpleSearch boolean not null, rendering_id int4, primary key (id));
create table cris_rp_prop (id int4 not null, endDate timestamp, startDate timestamp, lockDef int4, positionDef int4 not null, visibility int4, scopeDef_id int4, value_id int4, parent_id int4, typo_id int4, primary key (id));
create table cris_rp_tab (id int4 not null, ext varchar(255), mandatory boolean not null, mime varchar(255), priority int4 not null, shortName varchar(255), title varchar(255), visibility int4, primary key (id));
create table cris_rp_tab2box (cris_rp_tab_id int4 not null, cris_rp_box_id int4 not null);
create table cris_rp_tab2policygroup (tab_id int4 not null, authorizedGroup varchar(255));
create table cris_rp_tab2policysingle (tab_id int4 not null, authorizedSingle varchar(255));
create table cris_rp_wfile (id int4 not null, fileDescription text, labelAnchor varchar(255), showPreview boolean not null, widgetSize int4, useInStatistics boolean not null, primary key (id));
create table cris_rp_wpointer (id int4 not null, display text, filtro text, indexName varchar(255), widgetSize int4, target varchar(255), urlPath varchar(255), primary key (id));
create table cris_rpage (id int4 not null, crisID varchar(255), sourceID varchar(255), sourceRef varchar(255), status boolean, uuid varchar(255) not null, epersonID int4, namesTimestampLastModified timestamp, timestampCreated timestamp, timestampLastModified timestamp, primary key (id));
create table cris_statsubscription (id int4 not null, epersonID int4 not null, freq int4 not null, typeDef int4, handle_or_uuid varchar(255), primary key (id));
create table cris_subscription (id int4 not null, epersonID int4 not null, typeDef int4, uuid varchar(255), primary key (id));
create table cris_weperson (id int4 not null, filter text, primary key (id));
create table cris_wgroup (id int4 not null, filter text, primary key (id));
create table cris_ws_criteria (id int4 not null, criteria varchar(255), enabled boolean not null, filter varchar(255), primary key (id));
create table cris_ws_user (id int4 not null, enabled boolean not null, password varchar(255), username varchar(255), showHiddenMetadata boolean not null, fromIP varchar(255), toIP varchar(255), token varchar(255), timestampCreated timestamp, timestampLastModified timestamp, typeDef varchar(255), primary key (id));
create table cris_ws_user2crit (cris_ws_user_id int4 not null, criteria_id int4 not null);
create table jdyna_box_message (id int4 not null, body varchar(4000), showInEdit boolean not null, showInPublicView boolean not null, useBodyAsKeyMessageBundle boolean not null, elementAfter_id int4, parent_id int4, primary key (id));
create table jdyna_containable (DTYPE varchar(31) not null, id int4 not null, externalJSP varchar(255), cris_rp_pdef_fk int4, cris_pj_pdef_fk int4, cris_ou_pdef_fk int4, cris_rp_no_pdef_fk int4, cris_pj_no_pdef_fk int4, cris_ou_no_pdef_fk int4, cris_rp_no_tp int4, cris_pj_no_tp int4, cris_ou_no_tp_fk int4, cris_do_no_tp_fk int4, cris_do_no_pdef_fk int4, cris_do_pdef_fk int4, primary key (id));
create table jdyna_scopedefinition (id int4 not null, label varchar(255), primary key (id));
create table jdyna_values (DTYPE varchar(31) not null, id int4 not null, sortValue varchar(255), dateValue timestamp, textValue text, linkdescription varchar(255), linkvalue varchar(255), fileextension varchar(255), filefolder varchar(255), filemime varchar(255), filename varchar(255), doubleValue float8, booleanValue boolean, customPointer int4, rpvalue int4, projectvalue int4, ouvalue int4, dovalue int4, classificationvalue int4, primary key (id));
create table jdyna_widget_boolean (id int4 not null, checked boolean not null, hideWhenFalse boolean not null, showAsType varchar(255), primary key (id));
create table jdyna_widget_checkradio (id int4 not null, dropdown boolean, option4row int4, staticValues varchar(255), primary key (id));
create table jdyna_widget_classification (id int4 not null, chooseOnlyLeaves boolean not null, display text, treeObjectType varchar(255) not null, metadataBuilderTree_id int4, rootResearchObject_id int4, primary key (id));
create table jdyna_widget_date (id int4 not null, maxYear int4, minYear int4, time boolean not null, primary key (id));
create table jdyna_widget_link (id int4 not null, labelHeaderLabel varchar(255), labelHeaderURL varchar(255), widgetSize int4 not null, primary key (id));
create table jdyna_widget_number (id int4 not null, max float8, min float8, precisionDef int4 not null, widgetSize int4, primary key (id));
create table jdyna_widget_text (id int4 not null, collisioni boolean, widgetcol int4, measurementUnitCol varchar(255), measurementUnitRow varchar(255), widgetrow int4, displayFormat varchar(4000), htmlToolbar varchar(255), multilinea boolean not null, regex varchar(4000), primary key (id));
alter table cris_do add constraint UK_axyopjjgby8wk57nvxplccsav unique (sourceID, sourceRef);
alter table cris_do add constraint UK_lwf3x8hoky43o0tmhft2xx363 unique (crisID);
alter table cris_do add constraint UK_n763e5vokfelyrpfiib21v2l5 unique (uuid);
alter table cris_do_box add constraint UK_v6fabcbpjckf0s3thor0nmik unique (shortName);
alter table cris_do_etab add constraint UK_d337eib6hxu3x6ykfcg1vcy28 unique (shortName);
alter table cris_do_no add constraint UK_j4k58w7yfne81romhpntibwcw unique (positionDef, typo_id, parent_id);
alter table cris_do_no add constraint UK_3mgx4yb4v0upkij4r5b99t97n unique (uuid);
alter table cris_do_no_pdef add constraint UK_2h1e7fmy2pysaq31p5ybixoxs unique (shortName);
alter table cris_do_no_pdef add constraint UK_149nsa7ytv7qrut612ku6q41m unique (rendering_id);
alter table cris_do_no_prop add constraint UK_ql98tb61x00eivr8kvkk3xepi unique (positionDef, typo_id, parent_id);
alter table cris_do_no_prop add constraint UK_l3806bpn18qo700jpvqrr3dug unique (value_id);
create index cris_do_no_pprop_idx on cris_do_no_prop (parent_id);
alter table cris_do_pdef add constraint UK_p72sarl4b6bfgxf2aftgefess unique (shortName);
alter table cris_do_pdef add constraint UK_jda99nktxqoikvs4ahd9i3x9p unique (rendering_id);
alter table cris_do_prop add constraint UK_8pyu132ihbsjey2b75jhmuo7n unique (positionDef, typo_id, parent_id);
alter table cris_do_prop add constraint UK_koqu9fgt8mgjby7b4s0t9dlaw unique (value_id);
create index cris_do_pprop_idx on cris_do_prop (parent_id);
alter table cris_do_tab add constraint UK_lg0v0db5imik19j5c6q0xjjl2 unique (shortName);
alter table cris_orgunit add constraint UK_i4pp67dodete5m7s56h10fumv unique (sourceID, sourceRef);
alter table cris_orgunit add constraint UK_bu9o48y8txkmbr6ru3fim2ibu unique (crisID);
alter table cris_orgunit add constraint UK_aa4yp11io20wa36ylfg4xfdoa unique (uuid);
alter table cris_ou_box add constraint UK_atueaj8hjabm3h7j6f2ytf5fy unique (shortName);
alter table cris_ou_etab add constraint UK_7qqb26e0ud1wvgd85ags4jxwm unique (shortName);
alter table cris_ou_no add constraint UK_iy0po7i44nkvy0kbtbod99bi0 unique (positionDef, typo_id, parent_id);
alter table cris_ou_no add constraint UK_eyg632stq6txlq27grdr78pxx unique (uuid);
alter table cris_ou_no_pdef add constraint UK_fqt69fnte3f4068rw5y1nd6oi unique (shortName);
alter table cris_ou_no_pdef add constraint UK_55ce46f7f9x0li1hfcd129ru6 unique (rendering_id);
alter table cris_ou_no_prop add constraint UK_i1pdeb1t3ewkwcb8yat65f5py unique (positionDef, typo_id, parent_id);
alter table cris_ou_no_prop add constraint UK_t3mji72s4ylld86l4lpo4bbwy unique (value_id);
create index cris_ou_no_pprop_idx on cris_ou_no_prop (parent_id);
alter table cris_ou_pdef add constraint UK_p09u6dryk05de3gj3odv5qs31 unique (shortName);
alter table cris_ou_pdef add constraint UK_bpk5vc9gwmtd5stayg1p3vm0p unique (rendering_id);
alter table cris_ou_prop add constraint UK_dksf87mmyrlooukffmxd53x0w unique (positionDef, typo_id, parent_id);
alter table cris_ou_prop add constraint UK_io81r7mscq9520roimofygkma unique (value_id);
create index cris_ou_pprop_idx on cris_ou_prop (parent_id);
alter table cris_ou_tab add constraint UK_k6lbtrcm07ah07gl740v0mp88 unique (shortName);
alter table cris_pj_box add constraint UK_fhxvjf3a1hlisot0l85u3cn22 unique (shortName);
alter table cris_pj_etab add constraint UK_jxh1o2lihahwrtpgypgmsqx6k unique (shortName);
alter table cris_pj_no add constraint UK_lj2wjl45vkjn4xy9xixr0llwk unique (positionDef, typo_id, parent_id);
alter table cris_pj_no add constraint UK_eurj0377j9stkcmum17lcrcfh unique (uuid);
alter table cris_pj_no_pdef add constraint UK_ku5m8gudvlnhbvkiq82f79827 unique (shortName);
alter table cris_pj_no_pdef add constraint UK_3rxjndshx9ls8irnw8lypq3dc unique (rendering_id);
alter table cris_pj_no_prop add constraint UK_jn8q61o9fsfwbxjxbifa42f6c unique (positionDef, typo_id, parent_id);
alter table cris_pj_no_prop add constraint UK_4v75xs3d3tu4fbn7g5isflcak unique (value_id);
create index cris_pj_no_pprop_idx on cris_pj_no_prop (parent_id);
alter table cris_pj_pdef add constraint UK_90mykqujesj06o4rft40ttvvb unique (shortName);
alter table cris_pj_pdef add constraint UK_3t66f8i894rg2w31rgk9y8yoo unique (rendering_id);
alter table cris_pj_prop add constraint UK_pis213kikr3ed0r4d4cu9xyat unique (positionDef, typo_id, parent_id);
alter table cris_pj_prop add constraint UK_1peqo5gj8ln34vc9puisuff14 unique (value_id);
create index cris_pj_pprop_idx on cris_pj_prop (parent_id);
alter table cris_pj_tab add constraint UK_9rnbmmhnb4m0c8tde2hctbbr4 unique (shortName);
alter table cris_project add constraint UK_oy7cfqyeh3m7noojdkwatck1y unique (sourceID, sourceRef);
alter table cris_project add constraint UK_8nyg47l3x5udf60ye4fry3kuq unique (crisID);
alter table cris_project add constraint UK_un2k30prqoitkc9ysm868lmb unique (uuid);
alter table cris_rp_box add constraint UK_tly6242eg9wvgoyc708v4tdgu unique (shortName);
alter table cris_rp_etab add constraint UK_rs8398qwck6pbopiwa2mrh02r unique (shortName);
alter table cris_rp_no add constraint UK_nehla00dhli6hei7eieckgmcx unique (positionDef, typo_id, parent_id);
alter table cris_rp_no add constraint UK_5iyqh8xwkxoj331v96xq7uciq unique (uuid);
alter table cris_rp_no_pdef add constraint UK_8xf699cskda6g9jb8dg29t7xp unique (shortName);
alter table cris_rp_no_pdef add constraint UK_t8eml5ery8pmds8qolr5afsiw unique (rendering_id);
alter table cris_rp_no_prop add constraint UK_kqys46mi5u645ns5v1dk6lvx5 unique (positionDef, typo_id, parent_id);
alter table cris_rp_no_prop add constraint UK_qju7toon13m8o7e1dyg3f9cn6 unique (value_id);
create index cris_rp_no_pprop_idx on cris_rp_no_prop (parent_id);
alter table cris_rp_pdef add constraint UK_hond8wot5dfih8ueyys4rmn10 unique (shortName);
alter table cris_rp_pdef add constraint UK_3g8eli16qd7jpdfs8syh8lumh unique (rendering_id);
alter table cris_rp_prop add constraint UK_necur1okxhsrir6kbt83tw5jy unique (positionDef, typo_id, parent_id);
alter table cris_rp_prop add constraint UK_kvm7bvfwb43oj1bj1rq3m9rsi unique (value_id);
create index cris_rp_pprop_idx on cris_rp_prop (parent_id);
alter table cris_rp_tab add constraint UK_j668yln54vtos8odgj77m3wp1 unique (shortName);
alter table cris_rpage add constraint UK_7t8vihywap4efa9ln90f0qsj5 unique (sourceID, sourceRef);
alter table cris_rpage add constraint UK_10v9loxwp3tte4ew9x0moprit unique (crisID);
alter table cris_rpage add constraint UK_nbdcfci6ie9l8mqht1xfukqbo unique (uuid);
alter table cris_rpage add constraint UK_1talwjgxw9fvx5omeodo7v3ut unique (epersonID);
alter table cris_ws_user2crit add constraint UK_f7w13ncatxg2ejk9h8853t0e8 unique (criteria_id);
create index jdyna_values_dtype_idx on jdyna_values (DTYPE);
alter table cris_do add constraint FK_fc0g67614fiog1dy2cnlgts1f foreign key (typo_id) references cris_do_tp;
alter table cris_do_box add constraint FK_ntnml3hwo0a5by5xpy4e2e0ls foreign key (typeDef_id) references cris_do_tp;
alter table cris_do_box2con add constraint FK_42kirt9te4ukaq20n98oi7wth foreign key (jdyna_containable_id) references jdyna_containable;
alter table cris_do_box2con add constraint FK_feyp8mgacp9ygamc8pt92x7yk foreign key (cris_do_box_id) references cris_do_box;
alter table cris_do_box2policygroup add constraint FK_fqxyx09rdfu2fdlml08828xk8 foreign key (box_id) references cris_do_box;
alter table cris_do_box2policysingle add constraint FK_mjladl11m2680hn8o4btb4lly foreign key (box_id) references cris_do_box;
alter table cris_do_etab add constraint FK_l3xunn2dors3jn64y4e4scmyx foreign key (displayTab_id) references cris_do_tab;
alter table cris_do_etab add constraint FK_o5hn6lb337u4d5vo4bv4q256a foreign key (typeDef_id) references cris_do_tp;
alter table cris_do_etab2box add constraint FK_8f7fxsvql6j7cajgxjxqd56ve foreign key (cris_do_box_id) references cris_do_box;
alter table cris_do_etab2box add constraint FK_64baaiyf1fitm5bshra6etc3m foreign key (cris_do_etab_id) references cris_do_etab;
alter table cris_do_etab2policygroup add constraint FK_notgna4379iv6h6gh90vqvgg2 foreign key (etab_id) references cris_do_etab;
alter table cris_do_etab2policysingle add constraint FK_9c541j5og0fn26aiig2ud2k2d foreign key (etab_id) references cris_do_etab;
alter table cris_do_no add constraint FK_lj7u53cpfv3gdf53314a5dsl4 foreign key (parent_id) references cris_do;
alter table cris_do_no add constraint FK_6rjevf54mfpe1ca57i0uek7l4 foreign key (typo_id) references cris_do_no_tp;
alter table cris_do_no add constraint FK_rtfotw4rot9comm1gbsqhv6wv foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_do_no_prop add constraint FK_iiq5be3e88fnn03ukmxprmrc8 foreign key (parent_id) references cris_do_no;
alter table cris_do_no_prop add constraint FK_3tfwo7k75ulljjnsytmdc0amg foreign key (typo_id) references cris_do_no_pdef;
alter table cris_do_no_prop add constraint FK_i2q351awy1y06p8pd8dn421s9 foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_do_no_prop add constraint FK_l3806bpn18qo700jpvqrr3dug foreign key (value_id) references jdyna_values;
alter table cris_do_no_tp2pdef add constraint FK_hc19x2qu140wub3c4uhphjxjm foreign key (cris_do_no_pdef_id) references cris_do_no_pdef;
alter table cris_do_no_tp2pdef add constraint FK_12pfysjupgid5q9hail2t7kkm foreign key (cris_do_no_tp_id) references cris_do_no_tp;
alter table cris_do_prop add constraint FK_n66nqhfm49o4cb0a7xjf3wjf4 foreign key (parent_id) references cris_do;
alter table cris_do_prop add constraint FK_htjfvut8d3lnm32n8t8gf4biu foreign key (typo_id) references cris_do_pdef;
alter table cris_do_prop add constraint FK_jlr0y5d8lu8xj56uyb64733dq foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_do_prop add constraint FK_koqu9fgt8mgjby7b4s0t9dlaw foreign key (value_id) references jdyna_values;
alter table cris_do_tab add constraint FK_r25voh0iig0nfpfxnbmw1pkc9 foreign key (typeDef_id) references cris_do_tp;
alter table cris_do_tab2box add constraint FK_5j0tups3dh0t71hik7tbswadt foreign key (cris_do_box_id) references cris_do_box;
alter table cris_do_tab2box add constraint FK_om77haktsepkfilfgy3pc7p7p foreign key (cris_do_tab_id) references cris_do_tab;
alter table cris_do_tab2policygroup add constraint FK_j7d7vi6lj4h5wictl9sh6lmot foreign key (tab_id) references cris_do_tab;
alter table cris_do_tab2policysingle add constraint FK_i6f2ks46ta2j5vs00erqo2ip5 foreign key (tab_id) references cris_do_tab;
alter table cris_do_tp2notp add constraint FK_mi7iigoxr0d8guue9vhgon7gu foreign key (cris_do_no_tp_id) references cris_do_no_tp;
alter table cris_do_tp2notp add constraint FK_jbdt5b6evuvp4jxlyfnqn6v2q foreign key (cris_do_tp_id) references cris_do_tp;
alter table cris_do_tp2pdef add constraint FK_4v7j00d9agaeif0bf6gf85or7 foreign key (cris_do_pdef_id) references cris_do_pdef;
alter table cris_do_tp2pdef add constraint FK_hk7i944vtmggefgiynexw5o8k foreign key (cris_do_tp_id) references cris_do_tp;
alter table cris_ou_box2con add constraint FK_7yxd3aw0qxxrcwxung4gq8h80 foreign key (jdyna_containable_id) references jdyna_containable;
alter table cris_ou_box2con add constraint FK_fsc0difnoaua4u7fkm8jetr12 foreign key (cris_ou_box_id) references cris_ou_box;
alter table cris_ou_box2policygroup add constraint FK_60gjy1oe2yrpm5180hfxaop3l foreign key (box_id) references cris_ou_box;
alter table cris_ou_box2policysingle add constraint FK_dllsgbtw3raif8edkidoeoi56 foreign key (box_id) references cris_ou_box;
alter table cris_ou_etab add constraint FK_se60wf2qk13js6yv6yybqn4q6 foreign key (displayTab_id) references cris_ou_tab;
alter table cris_ou_etab2box add constraint FK_ml1ju8ldgniedhkvu79dcqekj foreign key (cris_ou_box_id) references cris_ou_box;
alter table cris_ou_etab2box add constraint FK_t2u156eltj2jklbp2i50lvowq foreign key (cris_ou_etab_id) references cris_ou_etab;
alter table cris_ou_etab2policygroup add constraint FK_ctyvoar08kmyrksr21fs3wjch foreign key (etab_id) references cris_ou_etab;
alter table cris_ou_etab2policysingle add constraint FK_6cw0xrjng41aedd4mk76jcm39 foreign key (etab_id) references cris_ou_etab;
alter table cris_ou_no add constraint FK_plxej42s8pd8y30k9nikoo8sg foreign key (parent_id) references cris_orgunit;
alter table cris_ou_no add constraint FK_4mjygpu22jqrqmuguw97bfetm foreign key (typo_id) references cris_ou_no_tp;
alter table cris_ou_no add constraint FK_ro2m4yf4gx0alpidp7nl3a793 foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_ou_no_prop add constraint FK_9gh7csy78iwf030472kqufe8n foreign key (parent_id) references cris_ou_no;
alter table cris_ou_no_prop add constraint FK_1gjbbpoqiwaimk9jq8k4r0561 foreign key (typo_id) references cris_ou_no_pdef;
alter table cris_ou_no_prop add constraint FK_pkpxf46sdvmnsbb67xkeoy61w foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_ou_no_prop add constraint FK_t3mji72s4ylld86l4lpo4bbwy foreign key (value_id) references jdyna_values;
alter table cris_ou_no_tp2pdef add constraint FK_ox1f8oret8htox46phbvf7vu2 foreign key (cris_ou_no_pdef_id) references cris_ou_no_pdef;
alter table cris_ou_no_tp2pdef add constraint FK_lve22cr625xqxt9aq3jjcbckv foreign key (cris_ou_no_tp_id) references cris_ou_no_tp;
alter table cris_ou_prop add constraint FK_dbc0m858848m37xjg69itvn6c foreign key (parent_id) references cris_orgunit;
alter table cris_ou_prop add constraint FK_6lwoynw2n3pn8c6j99gop02us foreign key (typo_id) references cris_ou_pdef;
alter table cris_ou_prop add constraint FK_sklpgs6h6v1fvm4l13v274dta foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_ou_prop add constraint FK_io81r7mscq9520roimofygkma foreign key (value_id) references jdyna_values;
alter table cris_ou_tab2box add constraint FK_6ry05l6mlunqief8wram1770l foreign key (cris_ou_box_id) references cris_ou_box;
alter table cris_ou_tab2box add constraint FK_26abr8nect1rgqa6nkg9q68pt foreign key (cris_ou_tab_id) references cris_ou_tab;
alter table cris_ou_tab2policygroup add constraint FK_484l9q8ojjiuk522qwtj5c78w foreign key (tab_id) references cris_ou_tab;
alter table cris_ou_tab2policysingle add constraint FK_p3j0r630vykj5t6od5ysd4ikk foreign key (tab_id) references cris_ou_tab;
alter table cris_pj_box2con add constraint FK_979582b7r2cuagp0do33rg4tv foreign key (jdyna_containable_id) references jdyna_containable;
alter table cris_pj_box2con add constraint FK_1puywj4p437h0pt57ils2g90b foreign key (cris_pj_box_id) references cris_pj_box;
alter table cris_pj_box2policygroup add constraint FK_rbdf00op5aym7rchnqxtsc7bv foreign key (box_id) references cris_pj_box;
alter table cris_pj_box2policysingle add constraint FK_ol4361xb7guetm6mlrltokeur foreign key (box_id) references cris_pj_box;
alter table cris_pj_etab add constraint FK_tljn2ea23dsl60m23juaeptrr foreign key (displayTab_id) references cris_pj_tab;
alter table cris_pj_etab2box add constraint FK_596ktsjh8y2wpao9kdpmkjgch foreign key (cris_pj_box_id) references cris_pj_box;
alter table cris_pj_etab2box add constraint FK_5wwskh39en2j2j8hl2oxhb2n6 foreign key (cris_pj_etab_id) references cris_pj_etab;
alter table cris_pj_etab2policygroup add constraint FK_cpnidos6chf15smpf365k9u2d foreign key (etab_id) references cris_pj_etab;
alter table cris_pj_etab2policysingle add constraint FK_c370hgq2gwt1fk1cpn92y5wof foreign key (etab_id) references cris_pj_etab;
alter table cris_pj_no add constraint FK_hgv396785eederv2vymqhc40e foreign key (parent_id) references cris_project;
alter table cris_pj_no add constraint FK_i5sc6s2ipvjmnkvhfl79ouby1 foreign key (typo_id) references cris_pj_no_tp;
alter table cris_pj_no add constraint FK_d3u1id11dh8cpu6byv4peecu8 foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_pj_no_prop add constraint FK_ctn25cliysoq7clconn2dvsy0 foreign key (parent_id) references cris_pj_no;
alter table cris_pj_no_prop add constraint FK_49w223c1hcycmpaxx8d791msm foreign key (typo_id) references cris_pj_no_pdef;
alter table cris_pj_no_prop add constraint FK_26xeivbhdu54r5dfj1v99cxvt foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_pj_no_prop add constraint FK_4v75xs3d3tu4fbn7g5isflcak foreign key (value_id) references jdyna_values;
alter table cris_pj_no_tp2pdef add constraint FK_63yffuhpaitj8s3p89ki0oa5r foreign key (cris_pj_no_pdef_id) references cris_pj_no_pdef;
alter table cris_pj_no_tp2pdef add constraint FK_htjuhq3qadf5iwkgu5qcra10w foreign key (cris_pj_no_tp_id) references cris_pj_no_tp;
alter table cris_pj_prop add constraint FK_guaxj0xrqnvv3cmi9c63keyqt foreign key (parent_id) references cris_project;
alter table cris_pj_prop add constraint FK_ocg1yq0sdhnc6mr5q65kyurh foreign key (typo_id) references cris_pj_pdef;
alter table cris_pj_prop add constraint FK_178mccanh2h10r0cqunwluydd foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_pj_prop add constraint FK_1peqo5gj8ln34vc9puisuff14 foreign key (value_id) references jdyna_values;
alter table cris_pj_tab2box add constraint FK_nxxmyq2joa0w27qj4hre5f233 foreign key (cris_pj_box_id) references cris_pj_box;
alter table cris_pj_tab2box add constraint FK_gb21mqf16af5stu85v7txma2b foreign key (cris_pj_tab_id) references cris_pj_tab;
alter table cris_pj_tab2policygroup add constraint FK_amf69chwwq9ktp2fbj0tagt3a foreign key (tab_id) references cris_pj_tab;
alter table cris_pj_tab2policysingle add constraint FK_456mu7altf23l6u163l255erc foreign key (tab_id) references cris_pj_tab;
alter table cris_pmc_citation2record add constraint FK_cby7u82jsnkaftqmtex8ic217 foreign key (pmcRecords_pmcID) references cris_pmc_record;
alter table cris_pmc_citation2record add constraint FK_4lx8k0ctp1qm5p1q0n4i0aphv foreign key (cris_pmc_citation_pubmedid) references cris_pmc_citation;
alter table cris_pmc_citation_itemids add constraint FK_uaclfo4bhxgeogwqughnn873 foreign key (cris_pmc_citation_pubmedid) references cris_pmc_citation;
alter table cris_pmc_record_handles add constraint FK_b854xw5cmjlyxdj2iy0w5nd2f foreign key (cris_pmc_record_pmcid) references cris_pmc_record;
alter table cris_pmc_record_pubmedids add constraint FK_rt7mkcemvbusg77nq99y3jnap foreign key (cris_pmc_record_pmcid) references cris_pmc_record;
alter table cris_rp_box2con add constraint FK_bkfyhin956c9tsyutk46n0m12 foreign key (jdyna_containable_id) references jdyna_containable;
alter table cris_rp_box2con add constraint FK_eaidxya38dy4q8jc45jpnb7oq foreign key (cris_rp_box_id) references cris_rp_box;
alter table cris_rp_box2policygroup add constraint FK_pwxgxcddbve4x9h92iqtxxpff foreign key (box_id) references cris_rp_box;
alter table cris_rp_box2policysingle add constraint FK_ritnnjkrjlp044yjo0tfpt19f foreign key (box_id) references cris_rp_box;
alter table cris_rp_etab add constraint FK_f7m2267gwolx9w41i74u5tc1k foreign key (displayTab_id) references cris_rp_tab;
alter table cris_rp_etab2box add constraint FK_bgo65obl0hi1jvvtrsvm43f5e foreign key (cris_rp_box_id) references cris_rp_box;
alter table cris_rp_etab2box add constraint FK_72lwmptu2ykcn4nwpkr3gro4x foreign key (cris_rp_etab_id) references cris_rp_etab;
alter table cris_rp_etab2policygroup add constraint FK_i8ye9656ab432x6ylqvi3eiek foreign key (etab_id) references cris_rp_etab;
alter table cris_rp_etab2policysingle add constraint FK_r9o249od95444ipvgrnij3uvl foreign key (etab_id) references cris_rp_etab;
alter table cris_rp_no add constraint FK_rtkbs1o75hf9e8kcekrfiplhk foreign key (parent_id) references cris_rpage;
alter table cris_rp_no add constraint FK_kxbhjy2ypu53wohes7v9yme7s foreign key (typo_id) references cris_rp_no_tp;
alter table cris_rp_no add constraint FK_f92khqsumj1vb427ohr88k9tv foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_rp_no_prop add constraint FK_8kulyp6twm998jusn47xmkagx foreign key (parent_id) references cris_rp_no;
alter table cris_rp_no_prop add constraint FK_3p0ine0gjssp40kr232qc4dfg foreign key (typo_id) references cris_rp_no_pdef;
alter table cris_rp_no_prop add constraint FK_fbt8f4suc8p8qfodkt1ba8fvq foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_rp_no_prop add constraint FK_qju7toon13m8o7e1dyg3f9cn6 foreign key (value_id) references jdyna_values;
alter table cris_rp_no_tp2pdef add constraint FK_rjvpjkt5g36c6sjvq92e5ufcb foreign key (cris_rp_no_pdef_id) references cris_rp_no_pdef;
alter table cris_rp_no_tp2pdef add constraint FK_o6pha8eq9luubu3ee9gy2dmwi foreign key (cris_rp_no_tp_id) references cris_rp_no_tp;
alter table cris_rp_prop add constraint FK_m67jrglhhmlk32ru3tlx9iqyt foreign key (parent_id) references cris_rpage;
alter table cris_rp_prop add constraint FK_kqnh5hofvg2cs7279gspf8fo5 foreign key (typo_id) references cris_rp_pdef;
alter table cris_rp_prop add constraint FK_fqxm0cldj5v8n94lv26uo7hb5 foreign key (scopeDef_id) references jdyna_scopedefinition;
alter table cris_rp_prop add constraint FK_kvm7bvfwb43oj1bj1rq3m9rsi foreign key (value_id) references jdyna_values;
alter table cris_rp_tab2box add constraint FK_kvxytofsjgknmsauoigoewxf6 foreign key (cris_rp_box_id) references cris_rp_box;
alter table cris_rp_tab2box add constraint FK_q92eq93wy5w54mkj9stvt4rsi foreign key (cris_rp_tab_id) references cris_rp_tab;
alter table cris_rp_tab2policygroup add constraint FK_ajnk574oowmgpud4o9kpctlp foreign key (tab_id) references cris_rp_tab;
alter table cris_rp_tab2policysingle add constraint FK_7dme5a998b5cffs2ynyk94l5d foreign key (tab_id) references cris_rp_tab;
alter table cris_ws_user2crit add constraint FK_f7w13ncatxg2ejk9h8853t0e8 foreign key (criteria_id) references cris_ws_criteria;
alter table cris_ws_user2crit add constraint FK_46u3xn2bav1ob8krk7ely7jbw foreign key (cris_ws_user_id) references cris_ws_user;
alter table jdyna_box_message add constraint FK_m2jh58o659lmgu5i38kn6u3m foreign key (elementAfter_id) references jdyna_containable;
alter table jdyna_containable add constraint FK_k2qp7i6sl0jjdoxs1n8r6v5bh foreign key (cris_rp_pdef_fk) references cris_rp_pdef;
alter table jdyna_containable add constraint FK_5p6h71hmt478puqichfyfj4j5 foreign key (cris_pj_pdef_fk) references cris_pj_pdef;
alter table jdyna_containable add constraint FK_jg0mkqo5ytopaxty2jo33ffxt foreign key (cris_ou_pdef_fk) references cris_ou_pdef;
alter table jdyna_containable add constraint FK_kvcjf37sma26056y57e2ml9rr foreign key (cris_rp_no_pdef_fk) references cris_rp_no_pdef;
alter table jdyna_containable add constraint FK_mqlmkq5a8hcgw7yl6s0wrbuv2 foreign key (cris_pj_no_pdef_fk) references cris_pj_no_pdef;
alter table jdyna_containable add constraint FK_dnvg24jur0c50hm16sxyvlcxv foreign key (cris_ou_no_pdef_fk) references cris_ou_no_pdef;
alter table jdyna_containable add constraint FK_7robphe5jdp8safh6mucsl7a0 foreign key (cris_rp_no_tp) references cris_rp_no_tp;
alter table jdyna_containable add constraint FK_pq1waf5pa60bat6xnhil687c2 foreign key (cris_pj_no_tp) references cris_pj_no_tp;
alter table jdyna_containable add constraint FK_psrgtjgk39p3s1ntnhschukn foreign key (cris_ou_no_tp_fk) references cris_ou_no_tp;
alter table jdyna_containable add constraint FK_b05fvc02kjcodwg2dx10cnowm foreign key (cris_do_no_tp_fk) references cris_do_no_tp;
alter table jdyna_containable add constraint FK_l7miyy3hrckebq5996mibby6b foreign key (cris_do_no_pdef_fk) references cris_do_no_pdef;
alter table jdyna_containable add constraint FK_7ycftv8mg6y0ctrx11h6imbg9 foreign key (cris_do_pdef_fk) references cris_do_pdef;
alter table jdyna_values add constraint FK_epb6ms4019hjnrsyp448iyuo8 foreign key (rpvalue) references cris_rpage;
alter table jdyna_values add constraint FK_t114s8de29b62b9537rnoim24 foreign key (projectvalue) references cris_project;
alter table jdyna_values add constraint FK_20pdqf2vc1sjqs36j3oab88wu foreign key (ouvalue) references cris_orgunit;
alter table jdyna_values add constraint FK_7kmuljw6d7w45hfbte39oasq8 foreign key (dovalue) references cris_do;
alter table jdyna_values add constraint FK_boathxpid9tfmswl65g8fsofe foreign key (classificationvalue) references cris_do;
alter table jdyna_widget_classification add constraint FK_ob081b8crx6qakbqj9y9l83ea foreign key (metadataBuilderTree_id) references cris_do_pdef;
alter table jdyna_widget_classification add constraint FK_8fup73lnpgx6c1fjqdhvhvn6 foreign key (rootResearchObject_id) references cris_do;
create sequence CRIS_DYNAOBJ_SEQ;
create sequence CRIS_METRICS_SEQ;
create sequence CRIS_ORCIDHISTORY_SEQ;
create sequence CRIS_ORCIDQUEUE_SEQ;
create sequence CRIS_OU_SEQ;
create sequence CRIS_PROJECT_SEQ;
create sequence CRIS_RELPREF_SEQ;
create sequence CRIS_RPAGE_SEQ;
create sequence CRIS_STATSUBSCRIPTION_SEQ;
create sequence CRIS_SUBSCRIPTION_SEQ;
create sequence CRIS_TYPODYNAOBJ_SEQ;
create sequence CRIS_WS_CRITERIA_SEQ;
create sequence CRIS_WS_USER_SEQ;
create sequence JDYNA_BOX_SEQ;
create sequence JDYNA_CONTAINABLE_SEQ;
create sequence JDYNA_MESSAGEBOX_SEQ;
create sequence JDYNA_NESTEDOBJECT_SEQ;
create sequence JDYNA_PDEF_SEQ;
create sequence JDYNA_PROP_SEQ;
create sequence JDYNA_SCOPEDEF_SEQ;
create sequence JDYNA_TAB_SEQ;
create sequence JDYNA_TYPONESTEDOBJECT_SEQ;
create sequence JDYNA_VALUES_SEQ;
create sequence JDYNA_WIDGET_SEQ;
   
-- Table to mantain the potential match between item and rp --
CREATE TABLE potentialmatches
(
   potentialmatches_id integer, 
   item_id integer, 
   rp character varying(20), 
   pending integer,
    PRIMARY KEY (potentialmatches_id)
);
CREATE SEQUENCE potentialmatches_seq;
CREATE INDEX rp_idx
   ON potentialmatches (rp ASC NULLS LAST);
CREATE INDEX pending_idx
   ON potentialmatches (pending);
-- END potential matches --