alter table cris_organizationunit add column crisID varchar(255) unique;
alter table cris_project add column crisID varchar(255) unique;
alter table cris_researcherpage add column crisID varchar(255) unique;
alter table cris_ou_nestedobject_prop add column lock int4;
alter table cris_ou_nestedobject_prop add column scope varchar(255);
alter table cris_ou_prop add column lock int4;
alter table cris_ou_prop add column scope varchar(255);
alter table cris_project_nestedobject_prop add column lock int4;
alter table cris_project_nestedobject_prop add column scope varchar(255);
alter table cris_project_prop add column lock int4;
alter table cris_project_prop add column scope varchar(255);
alter table cris_rp_nestedobject_prop add column lock int4;
alter table cris_rp_nestedobject_prop add column scope varchar(255);
alter table cris_rp_prop add column lock int4;
alter table cris_rp_prop add column scope varchar(255);
alter table jdyna_nestedobject_prop add column lock int4;
alter table jdyna_nestedobject_prop add column scope varchar(255);
