/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * http://www.dspace.org/license/
 */
package org.dspace.util;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import org.apache.solr.common.SolrDocument;
import org.dspace.content.authority.Choice;
import org.dspace.content.authority.ItemAuthorityExtraMetadataGenerator;
import org.dspace.utils.DSpace;

/**
 * Utility class for building authority-related metadata and choice objects.
 *
 * <p>This class provides static utility methods for extracting and processing
 * metadata from Solr documents to create enriched authority choices for
 * frontend auto-population and enhanced user experience.</p>
 *
 * @author Mykhaylo Boychuk (4science.it)
 */
public class ItemAuthorityUtils {

    private static final DSpace dspace = new DSpace();

    private ItemAuthorityUtils() {
    }

    /**
     * Builds a map of extra metadata for authority choices using registered metadata generators.
     * 
     * <p>This method extracts additional metadata from a Solr document and formats it for
     * frontend auto-population. The extra metadata is generated by all registered
     * {@link ItemAuthorityExtraMetadataGenerator} implementations and can include data-
     * prefixed keys for automatic form field mapping.</p>
     * 
     * <p>Additionally handles alternative names by creating a pipe-separated list of
     * alternative display names when multiple objectNames are provided.</p>
     *
     * @param authorityName the name of the authority requesting the extra data
     * @param item         the Solr document representing the DSpace item
     * @param objectNames  list of alternative display names for the item
     * @param uuid         the UUID of the item for reference linking
     * @return a map of metadata keys to values for frontend consumption
     */
    public static Map<String, String> buildExtra(String authorityName, SolrDocument item,
                                                 List<String> objectNames, String uuid) {
        Map<String, String> extras = new HashMap<String, String>();
        List<ItemAuthorityExtraMetadataGenerator> generators = dspace.getServiceManager()
                                                                     .getServicesByType(
                                                                         ItemAuthorityExtraMetadataGenerator.class);
        if (generators != null) {
            for (ItemAuthorityExtraMetadataGenerator gg : generators) {
                Map<String, String> extrasTmp = gg.build(authorityName, item);
                extras.putAll(extrasTmp);
            }
        }
        Set<String> alternativeNames = new TreeSet<>(objectNames);
        if (alternativeNames.size() > 1) {
            String alternativeNameKey = "alternative-names";
            alternativeNames.forEach(alternativeName -> {
                String alternative = alternativeName + "::" + uuid;
                if (extras.containsKey(alternativeNameKey)) {
                    extras.put(alternativeNameKey, extras.get(alternativeNameKey) + "|||" + alternative);
                } else {
                    extras.put(alternativeNameKey, alternative);
                }
            });
        }
        return extras;
    }

    /**
     * Builds aggregate choice objects from metadata generators for complex authority relationships.
     *
     * <p>This method collects {@link Choice} objects from all registered
     * {@link ItemAuthorityExtraMetadataGenerator} implementations, allowing for
     * complex authority structures where a single item can represent multiple
     * authority choices (e.g., when an item has multiple affiliations or roles).</p>
     *
     * <p>Each generator can contribute zero or more Choice objects, and this method
     * aggregates them all into a single collection for processing by the authority system.</p>
     *
     * @param authorityName the name of the authority requesting the aggregated choices
     * @param item          the Solr document representing the DSpace item
     * @return a list of Choice objects representing all possible authority selections
     */
    public static List<Choice> buildAggregateByExtra(String authorityName, SolrDocument item) {
        List<Choice> choiceList = new LinkedList<Choice>();
        List<ItemAuthorityExtraMetadataGenerator> generators = dspace.getServiceManager()
                                                                     .getServicesByType(
                                                                         ItemAuthorityExtraMetadataGenerator.class);
        if (generators != null) {
            for (ItemAuthorityExtraMetadataGenerator gg : generators) {
                choiceList.addAll(gg.buildAggregate(authorityName, item));
            }
        }
        return choiceList;
    }

}